ignore /\.git/

guard 'remote-sync',
        :source => ".", 
        :destination => '/home/gustavo/www/ps/modules/ebanx', 
        :user => 'gustavo',
	remote_port: 22,
	ssh: true,
	auth_key: '/home/gustavo/.ssh/id_rsa',
        :remote_address => 'integration.ebanx.com',
        :verbose => true, 
	exclude_from: nil,
        :cli => "--color", 
        :sync_on_start => true do

watch(%r{.*})
end

